version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: RedWeb-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: RedWeb-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: catalog_db
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: RedWeb-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  RabbitMQ:
    image: rabbitmq:4-management
    container_name: RedWeb-rabbitmq
    ports:
      - "5672:5672"   # AMQP Protocol
      - "15672:15672" # Web Dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

#  mock-bank:
#    build:
#      context: ./services/mock-bank
#      dockerfile: ../../services/payment-service/Dockerfile
#    container_name: ecommerce-mock-bank
#    ports:
#      - "9090:9090"
#    restart: unless-stopped

volumes:
  postgres_data:
  mongodb_data: