apiVersion: v1
kind: Service
metadata:
  name: postgres-ext-svc
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: RedWeb-infrastructure
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-ext-svc
subsets:
  - addresses:
      - ip: 192.168.0.6
    ports:
      - port: 5432