apiVersion: v1
kind: Service
metadata:
  name: redis-ext-svc
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: RedWeb-infrastructure
spec:
  type: ExternalName
  externalName: host.docker.internal
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-ext-svc
subsets:
  - addresses:
      - ip: 192.168.0.6
    ports:
      - port: 6379